server:
  port: 8085

spring:
  application:
    name: bookshop_gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication
              uri: http://localhost:8081/
              predicates:
                - Path=/authen/**
            - id: product
              uri: http://localhost:8082/
              predicates:
                - Path=/prod/**

