server:
  port: 9090

spring:
  application:
    name: bookshop_gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: bookshop_authentication_service
              uri: http://localhost:8081
              predicates:
                - Path=/authen/**

            - id: bookshop_product_service
              uri: http://localhost:8082
              predicates:
                - Path=/products/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty.http.client: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
