server:
  port: 8085

spring:
  application:
    name: bookshop_gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication
              uri: lb://AUTHENTICATION-SERVICE:8081/
              predicates:
                - Path=/authen/**
            - id: product
              uri: lb://PRODUCT-SERVICE:8082/
              predicates:
                - Path=/prod/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8086/eureka