server:
  port: 8085

spring:
  application:
    name: bookshop_gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: bookshop_authentication_service
              uri: http://localhost:8081
              predicates:
                - Path=/authen/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authCircuitBreaker
                    fallbackUri: forward:/fallback
#            - id: bookshop_product_service
#              uri: lb://PRODUCT_SERVICE
#              predicates:
#                - Path=/prod/**
#              filters:
#                - name: CircuitBreaker
#                  args:
#                    id: productCircuitBreakerId
#                    name: productCircuitBreaker
#                    fallbackUri: forward:/fallback

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty.http.client: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
